#!/bin/sh

# PROVIDE: cubesql
# REQUIRE: DAEMON linux
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="cubesql"
command="/usr/local/bin/cubesqlctl"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
restart_cmd="${name}_restart"

cubesql_start()
{
  ${command} start
}

cubesql_stop()
{
  ${command} stop
}

cubesql_restart()
{
  ${command} restart
}

load_rc_config $name
run_rc_command "$1"
